### ISSUE TITLE
[FEATURE] Translate the README file to Turkish

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/CS-Space#55]
It is necessary to translate the [`README.md`](https://github.com/Fire-Oceann/CS-Space#readme) file into Turkish.
[README/README-TR.md](https://github.com/Fire-Oceann/CS-Space/blob/main/README/README-TR.md)

**Comment by Anuran12** [comment]
@ziarparvaiz okay i will send the pr tomorrow morning

**Comment by ziarparvaiz** [comment]
> @ziarparvaiz okay i will send the pr tomorrow morning

Okay no problem
