### ISSUE TITLE
[FEATURE] Translate the README file to Russian

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/CS-Space#58]
It is necessary to translate the [`README.md`](https://github.com/Fire-Oceann/CS-Space#readme) file into Russian.
[README/README-RU.md](https://github.com/Fire-Oceann/CS-Space/blob/main/README/README-RU.md)

**Comment by streetcodec** [comment]
Please assign this to me! @ziarparvaiz
