### ISSUE TITLE
[FEATURE] Translate the README file to Italian

### ISSUE THREAD

**Issue by ziarparvaiz** [Fire-Oceann/CS-Space#59]
It is necessary to translate the [`README.md`](https://github.com/Fire-Oceann/CS-Space#readme) file into Italian.
[README/README-IT.md](https://github.com/Fire-Oceann/CS-Space/blob/main/README/README-IT.md)

**Comment by 3t8** [comment]
I'd like to work on this

**Comment by ziarparvaiz** [comment]
@3t8 Okay please open new bug issue
